from knowledgator_spacy_vector_matcher.matcher import VectorMatcher
from knowledgator_spacy_vector_matcher.utils import get_vector_for_matching
from knowledgator_spacy_vector_matcher.embedding_pipeline_component import add_embeddings_layer

__all__ = ["VectorMatcher", "add_embeddings_layer", "get_vector_for_matching"]